# === FILE: config.yaml ===
cameras:
  camera1:
    anchors:
      - id: "cam1_zone1"
        name: "Entrance Left"
        box: [191, 229, 412, 626 ] # x1, y1, x2, y2


  camera2:
    anchors:
      - id: "cam2_zone1"
        name: "Entrance Left"
        box: [117, 247, 381, 637 ] # x1, y1, x2, y2 

  camera3:
    anchors:
      - id: "cam3_zone1"
        name: "Entrance Left"
        box: [91, 220, 323, 619] # x1, y1, x2, y2

  camera4: 
    anchors:
      - id: "cam4_zone1"
        name: "Entrance Left"
        box: [108, 245, 332, 636] # x1, y1, x2, y2


camera_sockets:
  camera1: camera1_socket
  camera2: camera2_socket 
  camera3: camera3_socket
  camera4: camera4_socket
