services:
  smart_frame_selector:
    image: action_validator:0.1.0
    container_name: action_validator
    command: ["python", "main.py"]
    restart: always
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=compute,utility
      - frame_streamer_server_ip=frame_streamer
      - YOLO_CONFIG_DIR=/app/models/yolo
      - TZ=Asia/Tehran
    volumes:
      - .:/app
      - zmq_socket_ipc:/tmp:ro
    networks:
      - ai_vision

volumes:
  zmq_socket_ipc:
    name: zmq_socket_ipc
    external: true


networks:
  ai_vision:
    external: true
